baseurl = "http://csucsi.bulldogspecialista.hu/"
languageCode = "hu-hu"
title = "Csücsi Gazdát Keres"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
        # information about you and your website.
	name = "Adam Papai"
	description = "Csücsi vagyok, leszel a gazdim?"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Leszel a gazdim?"

		[params.navigation.links]
			about     = "Rólam"
			services  = "Igényeim"
			portfolio   = "Tulajdonságaim"
			contact   = "Kapcsolat"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Csücsi vagyok,<br/> és már megtaláltam ay új gazdámat!"
		subtitle   = "Köszönöm a sok megosztást! A segítségetekkel megtaláltam már az új gazdimat!"
		buttonText = "Tudj meg többet rólam!"


	# About section
	[params.about]
		headline    = "Ki is vagyok én?"
		description = "**2010.06.27**-én születtem. 6 éves, **kan bulldog** vagyok. Nem vagyok ivartalanítva. Az első gazdám a Boss nevet adta nekem, majd késöbb mivel mindig csücsültem a sarokban, rámragadt a Csücsi név, amit nagyon szeretek és hallgatok is rá. <br/><br/> Nagyon egészséges vagyok, kis koromban kellett csak a szememet megműteni - mint minden bulldognak - de azóta semmi bajom nem volt. Ez nem kis teljestmény egy bulldogtól! <br/><br/> Egy bulldoghoz képes nagyon sokat mozgok és futok. Jól bírom a mozgást. Más kutyákkal nagyon jól kijövök, legyen az kan vagy szuka. Szeretem a társaságot és szeretek játszani. Persze az alvást sem vetem meg. Viszont nem horkolok! Azért nem, mert jó nagy a légcsövem, így éjjel csendben vagyok. Ritka jó tulajdonság egy bulldogtól! <br/><br/> Sajnos a gazdimnak olyan helyre kell költöznie ahova csak repülővel lehet menni, mi pedig bulldogok ki vagyunk tiltva a repülőtársaságok járatairól. Ezért a gazdi megpróbál keresni nekem egy új gazdit, akivel boldog lehetek ismét. <br/><br/> Nagyon könnyen alkalmazkodom és hamar be tudok illeszkedni egy új családba."
		buttonText  = "Ugrás az igényeimhez"


	# Service section
	[params.services]
		headline = "Igényeim"

        [[params.services.list]]
            icon = "fa-futbol-o"
            title = "Labdázás"
            description = "Nagyon szeretek labdázni! Ha tehetném, egész nap csak labdáznék. Gyorsan futok és a levegőben is el tudom kapni."

        [[params.services.list]]
            icon = "fa-tint"
            title = "Friss víz"
            description = "Mindenem a friss víz. Ha koszos, akkor nem iszom bele, de ha tiszta, akkor nagyon sokat iszom belőle."

        [[params.services.list]]
            icon = "fa-cutlery"
            title = "Minőségi étel"
            description = "Gabonamentes kutyatáp. Lehetőleg marha-, bölény- vagy bárányhús, marha- és báránymáj."

        [[params.services.list]]
            icon = "fa-male"
            title = "Emberi közelség"
            description = "Szeretem ha emberek vesznek körül, a gyerekeket kifejezetten szeretem! Más kutyákkal nagyon jól kijövök!"

        [[params.services.list]]
            icon = "fa-bolt"
            title = "Figyelj rám"
            description = "Félek a villámlástól és a dörgésektől. Ilyenkor csak engedd meg hogy szorosan mellédbújhassak. Ez minden vágyam."

        [[params.services.list]]
            icon = "fa-sun-o"
            title = "Napozás"
            description = "A bulldogokkal ellentétben én imádok napozni. Süttetni magamat a napon. Kérlek engedd meg, hogy napozzak a kertben vagy a teraszon/erkélyen."


        [[params.services.list]]
            icon = "fa-heart"
            title = "Szeress"
            description = "Legyél kedves hozzám és megértő. Néha simogass meg és kedves hangon beszélj hozzám. Meghálálom."

        [[params.services.list]]
            icon = "fa-paw"
            title = "Taníts"
            description = "Minél több dologra megtanítasz annál jobban fogjuk egymást érteni! Szeretek játékosan tanulni."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Bezár"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Vedd fel velem a kapcsolatot!"
		description = "Ha úgy gondolod, hogy szívesen lennél az új gazdám, ne habozz! Írj vagy hívj a lenti elérhetőségeken! Ha éppen nem vagyok elérhető, a gazdim biztosan szívesen válaszol a kérdéseidre."
		phone = "+36 30 33-55-735"
		email = "info@bulldogspecialista.hu"
